s|https://fonts.googleapis.com/css?family=#{$google_font_family}&display=swap|https://cdn.cncfstack.com/googleapis/google-font-sans-css.css|g
s|https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700&display=swap|https://cdn.cncfstack.com/css2%3Ffamily%3DRubik%3Awght%40300%3B400%3B500%3B600%3B700%26display%3Dswap|g
s|https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700&display=swap|https://cdn.cncfstack.com/css2%3Ffamily%3DTajawal%3Awght%40300%3B400%3B500%3B700%26display%3Dswap|g
s|https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i&display=swap|https://cdn.cncfstack.com/css%3Ffamily%3DOpen%2BSans%3A300%2C300i%2C400%2C400i%2C700%2C700i%26display%3Dswap|g
s|https://cdn.jsdelivr.net/npm/@docsearch/js@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/js%403.8.2|g
s|https://cdn.jsdelivr.net/npm/@docsearch/css@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/css%403.8.2|g
s|https://cdn.jsdelivr.net/npm/chart.js@2.9.2/dist/Chart.min.js|https://cdn.cncfstack.com/npm/npm/chart.js%402.9.2/dist/Chart.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/katex.min.css|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/katex.min.css|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/katex.min.css|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/katex.min.css|g
s|https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v27.0.1/dist/font-face.css|https://cdn.cncfstack.com/gh/rastikerdar/vazir-font%40v27.0.1/dist/font-face.css|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/contrib/auto-render.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/contrib/auto-render.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/contrib/mhchem.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/contrib/mhchem.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/katex.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/katex.min.js|g
s|https://cdn.jsdelivr.net/npm/mermaid@9.2.2/dist/mermaid.min.js|https://cdn.cncfstack.com/npm/mermaid%409.2.2/dist/mermaid.min.js|g
s|https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js|https://cdn.cncfstack.com/npm/redoc%40latest/bundles/redoc.standalone.js|g
s|https://unpkg.com/external-svg-loader@1.3.4/svg-loader.min.js|https://cdn.cncfstack.com/external-svg-loader%401.3.4/svg-loader.min.js|g
s|https://unpkg.com/lunr@2.3.9/lunr.min.js|https://cdn.cncfstack.com/lunr%402.3.9/lunr.min.js|g
s|https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css|https://cdn.cncfstack.com/npm/docsearch.js%402/dist/cdn/docsearch.min.css|g
s|https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js|https://cdn.cncfstack.com/npm/docsearch.js%402/dist/cdn/docsearch.min.js|g
s|https://cdn.jsdelivr.net/npm/minisearch@7.1.0/dist/umd/index.min.js|https://cdn.cncfstack.com/npm/minisearch%407.1.0/dist/umd/index.min.js|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui.css|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui.css|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui-bundle.js|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui-bundle.js|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui-standalone-preset.js|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui-standalone-preset.js|g
s|https://cdn.jsdelivr.net/npm/mermaid@%s/dist/mermaid.esm.min.mjs|https://cdn.cncfstack.com/npm/mermaid%40%s/dist/mermaid.esm.min.mjs|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/katex.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/katex.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/contrib/mhchem.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/contrib/mhchem.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/contrib/auto-render.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/contrib/auto-render.min.js|g
s|https://cdn.jsdelivr.net/npm/@docsearch/js@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/js%403.8.2|g
s|https://cdn.jsdelivr.net/npm/@docsearch/css@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/css%403.8.2|g
s|https://cdn.jsdelivr.net/npm/water.css@2/out/water.css|https://cdn.cncfstack.com/npm/water.css%402/out/water.css|g
s|https://unpkg.com/@lukeed/ms/dist/index.js|https://cdn.cncfstack.com/%40lukeed/ms/dist/index.js|g
s|https://unpkg.com/@lukeed/ms/dist/index.mjs|https://cdn.cncfstack.com/ms/dist/index.mjs|g
s|https://unpkg.com/@lukeed/ms/dist/index.min.js|https://cdn.cncfstack.com/%40lukeed/ms/dist/index.mjs|g
s|https://unpkg.com/cliui@7.0.1/index.mjs|https://cdn.cncfstack.com/cliui%407.0.1/index.mjs|g
s|https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json|https://cdn.cncfstack.com/gh/jshttp/mime-db%40master/db.jso|g
s|https://cdn.jsdelivr.net/npm/node-forge@1.0.0/dist/forge.min.js|https://cdn.cncfstack.com/npm/node-forge%401.0.0/dist/forge.min.js|g
s|https://unpkg.com/node-forge@1.0.0/dist/forge.min.js|https://cdn.cncfstack.com/node-forge%401.0.0/dist/forge.min.js|g
s|https://unpkg.com/make-error@1/dist/make-error.js|https://cdn.cncfstack.com/make-error%401/dist/make-error.js|g
s|http://unpkg.com/lru-cache@9/dist/mjs/index.min.mjs|https://cdn.cncfstack.com/lru-cache%409/dist/mjs/index.min.mjs|g
s|https://unpkg.com/eventemitter3@latest/umd/eventemitter3.min.js|https://cdn.cncfstack.com/eventemitter3%40latest/umd/eventemitter3.min.js|g
s|https://unpkg.com/browse/ts-node@latest/tsconfig.schema.json|https://cdn.cncfstack.com/browse/ts-node%40latest/tsconfig.schema.json|g
s|https://unpkg.com/@popperjs/core@2/dist/umd/popper.js|https://cdn.cncfstack.com/%40popperjs/core%402/dist/umd/popper.js|g
s|https://unpkg.com/@popperjs/core@2|https://cdn.cncfstack.com/%40popperjs/core%402|g
s|https://unpkg.com/@popperjs/core@^2.0.0|https://cdn.cncfstack.com/%40popperjs/core%40^2.0.0|g
s|https://unpkg.com/yargs-parser@19.0.0/browser.js|https://unpkg.com/yargs-parser%4019.0.0/browser.js|g
s|https://cdn-images.mailchimp.com/|https://cdn.cncfstack.com/|g
s|https://cdnjs.cloudflare.com/|https://cdn.cncfstack.com/|g
s|https://cdn.jsdelivr.net/|https://cdn.cncfstack.com/|g
s|https://code.jquery.com/|https://cdn.cncfstack.com/|g
s|https://maxcdn.bootstrapcdn.com/|https://cdn.cncfstack.com/|g
s|https://unpkg.com/|https://cdn.cncfstack.com/|g
s|https://www.google-analytics.com/|https://cdn.cncfstack.com/|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f386.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f386.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f9d1-200d-1f91d-200d-1f9d1.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f9d1-200d-1f91d-200d-1f9d1.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f4d6.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f4d6.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/2753.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/2753.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f310.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f310.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f528.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f528.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/2601.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/2601.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f511.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f511.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f449.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f449.svg|g
s|https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|https://cdn.cncfstack.com/css%3Ffamily%3DOpen%2BSans%3A300%2C400%2C600%2C700|g
s|https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js|https://cdn.cncfstack.com/npm/mermaid/dist/mermaid.min.js|g
s|https://unpkg.com/lunr/lunr.js|https://cdn.cncfstack.com/lunr/lunr.js|g
s|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css|https://cdn.cncfstack.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css|
