s|https://cdn.jsdelivr.net/npm/@docsearch/js@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/js%403.8.2|g
s|https://cdn.jsdelivr.net/npm/@docsearch/css@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/css%403.8.2|g
s|https://cdn.jsdelivr.net/npm/chart.js@2.9.2/dist/Chart.min.js|https://cdn.cncfstack.com/npm/npm/chart.js%402.9.2/dist/Chart.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/katex.min.css|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/katex.min.css|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/katex.min.css|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/katex.min.css|g
s|https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v27.0.1/dist/font-face.css|https://cdn.cncfstack.com/gh/rastikerdar/vazir-font%40v27.0.1/dist/font-face.css|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/contrib/auto-render.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/contrib/auto-render.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/contrib/mhchem.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/contrib/mhchem.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/katex.min.js|https://cdn.cncfstack.com/npm/katex%400.16.3/dist/katex.min.js|g
s|https://cdn.jsdelivr.net/npm/mermaid@9.2.2/dist/mermaid.min.js|https://cdn.cncfstack.com/npm/mermaid%409.2.2/dist/mermaid.min.js|g
s|https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js|https://cdn.cncfstack.com/npm/redoc%40latest/bundles/redoc.standalone.js|g
s|https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css|https://cdn.cncfstack.com/npm/docsearch.js%402/dist/cdn/docsearch.min.css|g
s|https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js|https://cdn.cncfstack.com/npm/docsearch.js%402/dist/cdn/docsearch.min.js|g
s|https://cdn.jsdelivr.net/npm/minisearch@7.1.0/dist/umd/index.min.js|https://cdn.cncfstack.com/npm/minisearch%407.1.0/dist/umd/index.min.js|g
s|https://cdn.jsdelivr.net/npm/mermaid@%s/dist/mermaid.esm.min.mjs|https://cdn.cncfstack.com/npm/mermaid%40%s/dist/mermaid.esm.min.mjs|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/katex.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/katex.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/contrib/mhchem.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/contrib/mhchem.min.js|g
s|https://cdn.jsdelivr.net/npm/katex@0.16.19/dist/contrib/auto-render.min.js|https://cdn.cncfstack.com/npm/katex%400.16.19/dist/contrib/auto-render.min.js|g
s|https://cdn.jsdelivr.net/npm/@docsearch/js@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/js%403.8.2|g
s|https://cdn.jsdelivr.net/npm/@docsearch/css@3.8.2|https://cdn.cncfstack.com/npm/%40docsearch/css%403.8.2|g
s|https://cdn.jsdelivr.net/npm/water.css@2/out/water.css|https://cdn.cncfstack.com/npm/water.css%402/out/water.css|g
s|https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json|https://cdn.cncfstack.com/gh/jshttp/mime-db%40master/db.jso|g
s|https://cdn.jsdelivr.net/npm/node-forge@1.0.0/dist/forge.min.js|https://cdn.cncfstack.com/npm/node-forge%401.0.0/dist/forge.min.js|g
s|https://cdn.jsdelivr.net/|https://cdn.cncfstack.com/|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f386.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f386.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f9d1-200d-1f91d-200d-1f9d1.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f9d1-200d-1f91d-200d-1f9d1.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f4d6.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f4d6.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/2753.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/2753.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f310.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f310.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f528.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f528.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/2601.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/2601.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f511.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f511.svg|g
s|https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/1f449.svg|https://cdn.cncfstack.com/gh/jdecked/twemoji%4015.1.0/assets/svg/1f449.svg|g
s|https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js|https://cdn.cncfstack.com/npm/mermaid/dist/mermaid.min.js|g
