s|https://unpkg.com/external-svg-loader@1.3.4/svg-loader.min.js|https://cdn.cncfstack.com/external-svg-loader%401.3.4/svg-loader.min.js|g
s|https://unpkg.com/lunr@2.3.9/lunr.min.js|https://cdn.cncfstack.com/lunr%402.3.9/lunr.min.js|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui.css|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui.css|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui-bundle.js|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui-bundle.js|g
s|https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui-standalone-preset.js|https://cdn.cncfstack.com/swagger-ui-dist%405.1.0/swagger-ui-standalone-preset.js|g
s|https://unpkg.com/@lukeed/ms/dist/index.js|https://cdn.cncfstack.com/%40lukeed/ms/dist/index.js|g
s|https://unpkg.com/@lukeed/ms/dist/index.mjs|https://cdn.cncfstack.com/ms/dist/index.mjs|g
s|https://unpkg.com/@lukeed/ms/dist/index.min.js|https://cdn.cncfstack.com/%40lukeed/ms/dist/index.mjs|g
s|https://unpkg.com/cliui@7.0.1/index.mjs|https://cdn.cncfstack.com/cliui%407.0.1/index.mjs|g
s|https://unpkg.com/node-forge@1.0.0/dist/forge.min.js|https://cdn.cncfstack.com/node-forge%401.0.0/dist/forge.min.js|g
s|https://unpkg.com/make-error@1/dist/make-error.js|https://cdn.cncfstack.com/make-error%401/dist/make-error.js|g
s|http://unpkg.com/lru-cache@9/dist/mjs/index.min.mjs|https://cdn.cncfstack.com/lru-cache%409/dist/mjs/index.min.mjs|g
s|https://unpkg.com/eventemitter3@latest/umd/eventemitter3.min.js|https://cdn.cncfstack.com/eventemitter3%40latest/umd/eventemitter3.min.js|g
s|https://unpkg.com/browse/ts-node@latest/tsconfig.schema.json|https://cdn.cncfstack.com/browse/ts-node%40latest/tsconfig.schema.json|g
s|https://unpkg.com/@popperjs/core@2/dist/umd/popper.js|https://cdn.cncfstack.com/%40popperjs/core%402/dist/umd/popper.js|g
s|https://unpkg.com/@popperjs/core@2|https://cdn.cncfstack.com/%40popperjs/core%402|g
s|https://unpkg.com/@popperjs/core@^2.0.0|https://cdn.cncfstack.com/%40popperjs/core%40^2.0.0|g
s|https://unpkg.com/yargs-parser@19.0.0/browser.js|https://unpkg.com/yargs-parser%4019.0.0/browser.js|g
s|https://unpkg.com/|https://cdn.cncfstack.com/|g
s|https://unpkg.com/lunr/lunr.js|https://cdn.cncfstack.com/lunr/lunr.js|g
